# Generated by Django 5.1.15 on 2026-06-17 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('handle', models.CharField(help_text='e.g. @marc', max_length=40)),
                ('avatar', models.CharField(blank=True, max_length=8)),
                ('writes', models.CharField(choices=[('en', 'English'), ('ja', '日本語')], default='en', max_length=2)),
                ('location_en', models.CharField(blank=True, max_length=80)),
                ('location_ja', models.CharField(blank=True, max_length=80)),
                ('role_en', models.CharField(blank=True, max_length=120)),
                ('role_ja', models.CharField(blank=True, max_length=120)),
                ('since_en', models.CharField(blank=True, max_length=120)),
                ('since_ja', models.CharField(blank=True, max_length=120)),
                ('bio_en', models.TextField(blank=True)),
                ('bio_ja', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('bikes', 'Bikes'), ('parts', 'Parts'), ('places', 'Places to Ride'), ('opinions', 'Opinions'), ('interviews', 'Interviews'), ('culture', 'Culture'), ('other', 'Other')], max_length=20)),
                ('date', models.DateField()),
                ('read_time', models.CharField(default='5 min', help_text="e.g. '9 min'", max_length=20)),
                ('orig', models.CharField(choices=[('en', 'English'), ('ja', '日本語')], default='en', help_text='The language this story was originally written in.', max_length=2)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('title_ja', models.CharField(blank=True, max_length=200)),
                ('sub_en', models.CharField(blank=True, max_length=400)),
                ('sub_ja', models.CharField(blank=True, max_length=400)),
                ('body_en', models.JSONField(blank=True, default=list)),
                ('body_ja', models.JSONField(blank=True, default=list)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('media_label', models.CharField(blank=True, max_length=80)),
                ('media_shape', models.CharField(choices=[('wide', '16:9'), ('', '4:3'), ('tall', '3:4')], default='wide', max_length=8)),
                ('published', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.author')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
