# Generated by Django 5.1.15 on 2026-06-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('bikes', 'Bike/Parts'), ('places', 'Places'), ('opinions', 'Opinions'), ('interviews', 'Interviews'), ('other', 'Other')], max_length=20),
        ),
    ]
