# Generated by Django 6.0.6 on 2026-06-22 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remap_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='read_time',
        ),
    ]
